ANSIBLE - Config Management tool

	Module
	Task
	play
	Playbook
	Role
	

   
    Ansible Installation
    1. Create a new file called 'ansible.repo' in 
    cd /etc/yum.repos.d
    vi ansible.repo
    
    2. Copy the following content into it:
    [Ansible]
    name = ansible
    baseurl = https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
    enabled = 1
    gpgcheck = 0 
    
    3. Run 'yum update' 
    rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum -y install ansible
    ansible --version
    

vim /etc/ansible/hosts
[server]
172.1.1.1 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=~/.ssh/server1.pem


ansible server -m raw -a "uptime"
ansible server --sudo -m raw -a "yum update -y"


mkdir -p /opt/ansible-demo && cd /opt/ansible-demo

vim install-httpd.yaml


---
- hosts: server

  tasks:
  - name: installing httpd
    yum:  pkg=httpd state=installed
    become: true


ansible-playbook install-httpd.yaml -v


vim install-httpd.yaml

---
- hosts: server
  gather_facts: no
  tasks:
  - name: installing httpd
    yum:  pkg=httpd state=installed
    become: true

  - name: Starting httpd
    service: name=httpd state=started
    become: true   

ansible-playbook install-httpd.yaml -v

vim install-httpd.yaml

---
- hosts: server
  gather_facts: no
  tasks:
  - name: installing httpd
    yum:  pkg=httpd state=installed
    become: true

  - name: Starting httpd
    service: name=httpd state=started
    become: true
    register: httpd_output

  - name: Printing httpd output
    debug: var=httpd_output

  - name: Marking my output
    debug: msg="My automation is successful"
    when: httpd_output is succeeded
~

ansible-playbook install-httpd.yaml -vv



vim publickeydemo.yml

---
- hosts: server

  tasks:
    - name: Copying public key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      become: true
~
~
~
~

ansible-playbook publickeydemo.yml -vv


